// Mocks generated by Mockito 5.4.6 from annotations
// in sigchos_smart_tourist/test/widgets/home/home_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sigchos_smart_tourist/domain/entities/emprendimiento.dart'
    as _i8;
import 'package:sigchos_smart_tourist/domain/entities/hosteria.dart' as _i7;
import 'package:sigchos_smart_tourist/domain/entities/lugar.dart' as _i6;
import 'package:sigchos_smart_tourist/domain/entities/ruta.dart' as _i2;
import 'package:sigchos_smart_tourist/domain/entities/usuario.dart' as _i3;
import 'package:sigchos_smart_tourist/domain/repositories/auth_repository.dart'
    as _i9;
import 'package:sigchos_smart_tourist/domain/repositories/lugares_repository.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRuta_0 extends _i1.SmartFake implements _i2.Ruta {
  _FakeRuta_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUsuario_1 extends _i1.SmartFake implements _i3.Usuario {
  _FakeUsuario_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LugaresRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLugaresRepository extends _i1.Mock implements _i4.LugaresRepository {
  MockLugaresRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i6.Lugar>> getLugares({String? tipo}) =>
      (super.noSuchMethod(
            Invocation.method(#getLugares, [], {#tipo: tipo}),
            returnValue: _i5.Future<List<_i6.Lugar>>.value(<_i6.Lugar>[]),
          )
          as _i5.Future<List<_i6.Lugar>>);

  @override
  _i5.Future<List<_i6.Lugar>> getLugaresCercanos(
    double? latitude,
    double? longitude,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLugaresCercanos, [latitude, longitude]),
            returnValue: _i5.Future<List<_i6.Lugar>>.value(<_i6.Lugar>[]),
          )
          as _i5.Future<List<_i6.Lugar>>);

  @override
  _i5.Future<void> createLugar(_i6.Lugar? lugar) =>
      (super.noSuchMethod(
            Invocation.method(#createLugar, [lugar]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateLugar(_i6.Lugar? lugar) =>
      (super.noSuchMethod(
            Invocation.method(#updateLugar, [lugar]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteLugar(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLugar, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i7.Hosteria>> getHosterias() =>
      (super.noSuchMethod(
            Invocation.method(#getHosterias, []),
            returnValue: _i5.Future<List<_i7.Hosteria>>.value(<_i7.Hosteria>[]),
          )
          as _i5.Future<List<_i7.Hosteria>>);

  @override
  _i5.Future<void> createHosteria(_i7.Hosteria? hosteria) =>
      (super.noSuchMethod(
            Invocation.method(#createHosteria, [hosteria]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateHosteria(_i7.Hosteria? hosteria) =>
      (super.noSuchMethod(
            Invocation.method(#updateHosteria, [hosteria]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteHosteria(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteHosteria, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i8.Emprendimiento>> getEmprendimientos({
    String? categoria,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getEmprendimientos, [], {#categoria: categoria}),
            returnValue: _i5.Future<List<_i8.Emprendimiento>>.value(
              <_i8.Emprendimiento>[],
            ),
          )
          as _i5.Future<List<_i8.Emprendimiento>>);

  @override
  _i5.Future<void> createEmprendimiento(_i8.Emprendimiento? emprendimiento) =>
      (super.noSuchMethod(
            Invocation.method(#createEmprendimiento, [emprendimiento]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateEmprendimiento(_i8.Emprendimiento? emprendimiento) =>
      (super.noSuchMethod(
            Invocation.method(#updateEmprendimiento, [emprendimiento]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteEmprendimiento(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEmprendimiento, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.Ruta>> getRutas() =>
      (super.noSuchMethod(
            Invocation.method(#getRutas, []),
            returnValue: _i5.Future<List<_i2.Ruta>>.value(<_i2.Ruta>[]),
          )
          as _i5.Future<List<_i2.Ruta>>);

  @override
  _i5.Future<_i2.Ruta> getRutaDetalle(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getRutaDetalle, [id]),
            returnValue: _i5.Future<_i2.Ruta>.value(
              _FakeRuta_0(this, Invocation.method(#getRutaDetalle, [id])),
            ),
          )
          as _i5.Future<_i2.Ruta>);

  @override
  _i5.Future<void> createRuta(_i2.Ruta? ruta) =>
      (super.noSuchMethod(
            Invocation.method(#createRuta, [ruta]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateRuta(_i2.Ruta? ruta) =>
      (super.noSuchMethod(
            Invocation.method(#updateRuta, [ruta]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteRuta(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRuta, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.Comentario>> getComentarios(
    String? id,
    String? tipoColeccion,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getComentarios, [id, tipoColeccion]),
            returnValue: _i5.Future<List<_i6.Comentario>>.value(
              <_i6.Comentario>[],
            ),
          )
          as _i5.Future<List<_i6.Comentario>>);

  @override
  _i5.Future<void> addComentario(
    String? id,
    String? tipoColeccion,
    _i6.Comentario? comentario,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addComentario, [id, tipoColeccion, comentario]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> addCalificacion(
    String? id,
    String? tipoColeccion,
    _i6.Calificacion? calificacion,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addCalificacion, [
              id,
              tipoColeccion,
              calificacion,
            ]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i9.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i3.Usuario?> get onAuthStateChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onAuthStateChanged),
            returnValue: _i5.Stream<_i3.Usuario?>.empty(),
          )
          as _i5.Stream<_i3.Usuario?>);

  @override
  _i5.Future<_i3.Usuario> signUp({
    required String? nombre,
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #nombre: nombre,
              #email: email,
              #password: password,
            }),
            returnValue: _i5.Future<_i3.Usuario>.value(
              _FakeUsuario_1(
                this,
                Invocation.method(#signUp, [], {
                  #nombre: nombre,
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Usuario>);

  @override
  _i5.Future<_i3.Usuario> signIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i5.Future<_i3.Usuario>.value(
              _FakeUsuario_1(
                this,
                Invocation.method(#signIn, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Usuario>);

  @override
  _i5.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> sendPasswordResetEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [email]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.Usuario?> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i5.Future<_i3.Usuario?>.value(),
          )
          as _i5.Future<_i3.Usuario?>);
}
