// Mocks generated by Mockito 5.4.6 from annotations
// in sigchos_smart_tourist/test/unit/domain/repositories/lugares_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sigchos_smart_tourist/core/network/network_info.dart' as _i9;
import 'package:sigchos_smart_tourist/data/datasources/local/local_lugares_datasource.dart'
    as _i8;
import 'package:sigchos_smart_tourist/data/datasources/remote/firestore_lugares_datasource.dart'
    as _i3;
import 'package:sigchos_smart_tourist/data/models/emprendimiento_model.dart'
    as _i7;
import 'package:sigchos_smart_tourist/data/models/hosteria_model.dart' as _i6;
import 'package:sigchos_smart_tourist/data/models/lugar_model.dart' as _i5;
import 'package:sigchos_smart_tourist/data/models/ruta_model.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRutaModel_0 extends _i1.SmartFake implements _i2.RutaModel {
  _FakeRutaModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FirestoreLugaresDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreLugaresDataSource extends _i1.Mock
    implements _i3.FirestoreLugaresDataSource {
  MockFirestoreLugaresDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.LugarModel>> getLugares({String? tipo}) =>
      (super.noSuchMethod(
            Invocation.method(#getLugares, [], {#tipo: tipo}),
            returnValue: _i4.Future<List<_i5.LugarModel>>.value(
              <_i5.LugarModel>[],
            ),
          )
          as _i4.Future<List<_i5.LugarModel>>);

  @override
  _i4.Future<List<_i5.LugarModel>> getLugaresCercanos(
    double? latitude,
    double? longitude,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLugaresCercanos, [latitude, longitude]),
            returnValue: _i4.Future<List<_i5.LugarModel>>.value(
              <_i5.LugarModel>[],
            ),
          )
          as _i4.Future<List<_i5.LugarModel>>);

  @override
  _i4.Future<void> createLugar(_i5.LugarModel? lugar) =>
      (super.noSuchMethod(
            Invocation.method(#createLugar, [lugar]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateLugar(_i5.LugarModel? lugar) =>
      (super.noSuchMethod(
            Invocation.method(#updateLugar, [lugar]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteLugar(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLugar, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.HosteriaModel>> getHosterias() =>
      (super.noSuchMethod(
            Invocation.method(#getHosterias, []),
            returnValue: _i4.Future<List<_i6.HosteriaModel>>.value(
              <_i6.HosteriaModel>[],
            ),
          )
          as _i4.Future<List<_i6.HosteriaModel>>);

  @override
  _i4.Future<void> createHosteria(_i6.HosteriaModel? hosteria) =>
      (super.noSuchMethod(
            Invocation.method(#createHosteria, [hosteria]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateHosteria(_i6.HosteriaModel? hosteria) =>
      (super.noSuchMethod(
            Invocation.method(#updateHosteria, [hosteria]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteHosteria(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteHosteria, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.EmprendimientoModel>> getEmprendimientos({
    String? categoria,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getEmprendimientos, [], {#categoria: categoria}),
            returnValue: _i4.Future<List<_i7.EmprendimientoModel>>.value(
              <_i7.EmprendimientoModel>[],
            ),
          )
          as _i4.Future<List<_i7.EmprendimientoModel>>);

  @override
  _i4.Future<void> createEmprendimiento(
    _i7.EmprendimientoModel? emprendimiento,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createEmprendimiento, [emprendimiento]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateEmprendimiento(
    _i7.EmprendimientoModel? emprendimiento,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateEmprendimiento, [emprendimiento]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteEmprendimiento(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEmprendimiento, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.RutaModel>> getRutas() =>
      (super.noSuchMethod(
            Invocation.method(#getRutas, []),
            returnValue: _i4.Future<List<_i2.RutaModel>>.value(
              <_i2.RutaModel>[],
            ),
          )
          as _i4.Future<List<_i2.RutaModel>>);

  @override
  _i4.Future<_i2.RutaModel> getRutaDetalle(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getRutaDetalle, [id]),
            returnValue: _i4.Future<_i2.RutaModel>.value(
              _FakeRutaModel_0(this, Invocation.method(#getRutaDetalle, [id])),
            ),
          )
          as _i4.Future<_i2.RutaModel>);

  @override
  _i4.Future<void> createRuta(_i2.RutaModel? ruta) =>
      (super.noSuchMethod(
            Invocation.method(#createRuta, [ruta]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateRuta(_i2.RutaModel? ruta) =>
      (super.noSuchMethod(
            Invocation.method(#updateRuta, [ruta]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteRuta(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRuta, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.ComentarioModel>> getComentarios(
    String? id,
    String? coleccionPadre,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getComentarios, [id, coleccionPadre]),
            returnValue: _i4.Future<List<_i5.ComentarioModel>>.value(
              <_i5.ComentarioModel>[],
            ),
          )
          as _i4.Future<List<_i5.ComentarioModel>>);

  @override
  _i4.Future<void> addComentario(
    String? id,
    String? coleccionPadre,
    _i5.ComentarioModel? comentario,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addComentario, [id, coleccionPadre, comentario]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> addCalificacion(
    String? id,
    String? coleccionPadre,
    _i5.CalificacionModel? calificacion,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addCalificacion, [
              id,
              coleccionPadre,
              calificacion,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [LocalLugaresDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalLugaresDataSource extends _i1.Mock
    implements _i8.LocalLugaresDataSource {
  MockLocalLugaresDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.LugarModel>> getCachedLugares() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedLugares, []),
            returnValue: _i4.Future<List<_i5.LugarModel>>.value(
              <_i5.LugarModel>[],
            ),
          )
          as _i4.Future<List<_i5.LugarModel>>);

  @override
  _i4.Future<void> cacheLugares(List<_i5.LugarModel>? lugares) =>
      (super.noSuchMethod(
            Invocation.method(#cacheLugares, [lugares]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.HosteriaModel>> getCachedHosterias() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedHosterias, []),
            returnValue: _i4.Future<List<_i6.HosteriaModel>>.value(
              <_i6.HosteriaModel>[],
            ),
          )
          as _i4.Future<List<_i6.HosteriaModel>>);

  @override
  _i4.Future<void> cacheHosterias(List<_i6.HosteriaModel>? hosterias) =>
      (super.noSuchMethod(
            Invocation.method(#cacheHosterias, [hosterias]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.EmprendimientoModel>> getCachedEmprendimientos() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedEmprendimientos, []),
            returnValue: _i4.Future<List<_i7.EmprendimientoModel>>.value(
              <_i7.EmprendimientoModel>[],
            ),
          )
          as _i4.Future<List<_i7.EmprendimientoModel>>);

  @override
  _i4.Future<void> cacheEmprendimientos(
    List<_i7.EmprendimientoModel>? emprendimientos,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cacheEmprendimientos, [emprendimientos]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.RutaModel>> getCachedRutas() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedRutas, []),
            returnValue: _i4.Future<List<_i2.RutaModel>>.value(
              <_i2.RutaModel>[],
            ),
          )
          as _i4.Future<List<_i2.RutaModel>>);

  @override
  _i4.Future<void> cacheRutas(List<_i2.RutaModel>? rutas) =>
      (super.noSuchMethod(
            Invocation.method(#cacheRutas, [rutas]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i9.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
