// Mocks generated by Mockito 5.4.6 from annotations
// in sigchos_smart_tourist/test/widgets/lugares/lugares_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sigchos_smart_tourist/domain/entities/emprendimiento.dart'
    as _i7;
import 'package:sigchos_smart_tourist/domain/entities/hosteria.dart' as _i6;
import 'package:sigchos_smart_tourist/domain/entities/lugar.dart' as _i5;
import 'package:sigchos_smart_tourist/domain/entities/ruta.dart' as _i2;
import 'package:sigchos_smart_tourist/domain/repositories/lugares_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRuta_0 extends _i1.SmartFake implements _i2.Ruta {
  _FakeRuta_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LugaresRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLugaresRepository extends _i1.Mock implements _i3.LugaresRepository {
  MockLugaresRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.Lugar>> getLugares({String? tipo}) =>
      (super.noSuchMethod(
            Invocation.method(#getLugares, [], {#tipo: tipo}),
            returnValue: _i4.Future<List<_i5.Lugar>>.value(<_i5.Lugar>[]),
          )
          as _i4.Future<List<_i5.Lugar>>);

  @override
  _i4.Future<List<_i5.Lugar>> getLugaresCercanos(
    double? latitude,
    double? longitude,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLugaresCercanos, [latitude, longitude]),
            returnValue: _i4.Future<List<_i5.Lugar>>.value(<_i5.Lugar>[]),
          )
          as _i4.Future<List<_i5.Lugar>>);

  @override
  _i4.Future<void> createLugar(_i5.Lugar? lugar) =>
      (super.noSuchMethod(
            Invocation.method(#createLugar, [lugar]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateLugar(_i5.Lugar? lugar) =>
      (super.noSuchMethod(
            Invocation.method(#updateLugar, [lugar]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteLugar(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLugar, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.Hosteria>> getHosterias() =>
      (super.noSuchMethod(
            Invocation.method(#getHosterias, []),
            returnValue: _i4.Future<List<_i6.Hosteria>>.value(<_i6.Hosteria>[]),
          )
          as _i4.Future<List<_i6.Hosteria>>);

  @override
  _i4.Future<void> createHosteria(_i6.Hosteria? hosteria) =>
      (super.noSuchMethod(
            Invocation.method(#createHosteria, [hosteria]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateHosteria(_i6.Hosteria? hosteria) =>
      (super.noSuchMethod(
            Invocation.method(#updateHosteria, [hosteria]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteHosteria(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteHosteria, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.Emprendimiento>> getEmprendimientos({
    String? categoria,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getEmprendimientos, [], {#categoria: categoria}),
            returnValue: _i4.Future<List<_i7.Emprendimiento>>.value(
              <_i7.Emprendimiento>[],
            ),
          )
          as _i4.Future<List<_i7.Emprendimiento>>);

  @override
  _i4.Future<void> createEmprendimiento(_i7.Emprendimiento? emprendimiento) =>
      (super.noSuchMethod(
            Invocation.method(#createEmprendimiento, [emprendimiento]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateEmprendimiento(_i7.Emprendimiento? emprendimiento) =>
      (super.noSuchMethod(
            Invocation.method(#updateEmprendimiento, [emprendimiento]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteEmprendimiento(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEmprendimiento, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Ruta>> getRutas() =>
      (super.noSuchMethod(
            Invocation.method(#getRutas, []),
            returnValue: _i4.Future<List<_i2.Ruta>>.value(<_i2.Ruta>[]),
          )
          as _i4.Future<List<_i2.Ruta>>);

  @override
  _i4.Future<_i2.Ruta> getRutaDetalle(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getRutaDetalle, [id]),
            returnValue: _i4.Future<_i2.Ruta>.value(
              _FakeRuta_0(this, Invocation.method(#getRutaDetalle, [id])),
            ),
          )
          as _i4.Future<_i2.Ruta>);

  @override
  _i4.Future<void> createRuta(_i2.Ruta? ruta) =>
      (super.noSuchMethod(
            Invocation.method(#createRuta, [ruta]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateRuta(_i2.Ruta? ruta) =>
      (super.noSuchMethod(
            Invocation.method(#updateRuta, [ruta]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteRuta(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRuta, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.Comentario>> getComentarios(
    String? id,
    String? tipoColeccion,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getComentarios, [id, tipoColeccion]),
            returnValue: _i4.Future<List<_i5.Comentario>>.value(
              <_i5.Comentario>[],
            ),
          )
          as _i4.Future<List<_i5.Comentario>>);

  @override
  _i4.Future<void> addComentario(
    String? id,
    String? tipoColeccion,
    _i5.Comentario? comentario,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addComentario, [id, tipoColeccion, comentario]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> addCalificacion(
    String? id,
    String? tipoColeccion,
    _i5.Calificacion? calificacion,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addCalificacion, [
              id,
              tipoColeccion,
              calificacion,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
